// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnwyugljppnswcvmqfbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxud3l1Z2xqcHBuc3djdm1xZmJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5OTQxMzAsImV4cCI6MjA3MTU3MDEzMH0.noJqjEa0VifCBxerxz6bjKPyA-gIZ6P4ZV-y2SJFMz4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});