// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxbiyioidczozrwkcpvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4Yml5aW9pZGN6b3pyd2tjcHZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NzA5NTMsImV4cCI6MjA2NTI0Njk1M30.ZAYRzjKTSSNynWA1RRFkoGSC0nL_myQRy0hOidxtxiw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});